name: Build Firmware

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Run esp-idf patch script
      run: ./patch-esp-idf.sh

    - name: Build ESP-IDF Firmware
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32s3       # Currently we only build for M5Cardputer (so esp32s3)
        path: 'Firmware/BeamStalker'

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.build_firmware.outcome == 'success'
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.pull_request.title }}
        tag_name: ${{ github.event.pull_request.title }}
        fail_on_unmatched_files: true
        files: |
          Firmware/BeamStalker/build/BeamStalker-v*.bin
