name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [doc-branch]

permissions: write-all

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: doc-branch
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./source
        requirements_path: ./requirements.txt
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        #destination_dir: docs 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
