name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [doc-branch]

permissions: write-all

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: doc-branch

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Debug Environment
      run: |
        echo "Debugging build environment..."
        ls -al /tmp || true

    - name: Run Sphinx Build
      run: |
        sphinx-build -b html ./source ./build/html --keep-going
      env:
        TMPDIR: ./tmp  # Restrict temporary directories to avoid scanning system folders.

    - name: Disable Jekyll
      run: touch ./build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        destination_dir: docs
        publish_dir: ./build/html
